#!/bin/sh
export MITGCM_DIR=/nesi/project/vuw03548/MITgcm-checkpoint67m


module load intel/2022a
module load  iimpi/2022a

mkdir build
cd build

rm -f *.o
rm -f *.f
make CLEAN
rm Makefile


${MITGCM_DIR}/tools/genmake2 "-rootdir" "${MITGCM_DIR}" "-mpi" "-mods" "../code" "-optfile" "../linux_amd64_ifort+impi"
make depend
make -j 8

cd ..

