# $Header: /u/gcmpack/MITgcm_contrib/gael/verification/global_oce_llc90/code/packages.conf,v 1.1 2012/10/03 20:27:37 gforget Exp $
# $Name:  $

#gfd : mom_common mom_fluxform mom_vecinv
#  generic_advdiff debug mdsio rw monitor
#gfd gmredi kpp = oceanic

 
gfd
gmredi
kpp
cd_code
#
cal
timeave
diagnostics
exch2
#
exf
obcs
bbl
seaice
shelfice
frazil
ptracers